name: Code Quality Checks
on: push

jobs:
  react-build-check:
    name: React.js Build Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Create React Build
        run: npm run build
