name: Code Quality Checks
on: push

jobs:
  ts-check:
    name: React Build Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Create React Build
        run: npm run build

  prettier-check:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run Prettier check on all source files
        run: npx prettier --check ./
